### ISSUE TITLE
Requirements needed from the bot

### ISSUE THREAD

**Issue by khsunny786** [MarkusGordathian/Kratos#12]
- [x] User notes
- [x] Muting capabilities with time constraints. E.g. Muting and unmuting after 10 
- [x] Giving muting capabilities to Trusted role
- [x] Banning capabilities with time constraints. E.g. Ban for 1 day etc
- [x] Blacklist
- [x] Whitelist of roles
- [ ] Ignore certain channels to apply rate limiting
- [x] "Mod list" of roles
- [x] Rate limiting
- [ ] Anti spam
- [x] Purge
- [x] Slowmode
- [x] Logging Moderator commands
- [x] Logging Server related changes. E.g. Nickname/Profile Name/Role changes. Deleted/Edited messages
- [x] Logging Bans
- [ ] Restart Commands
- [x] Change profile name/avatar commands
- [x] Master ID, whatever this ID is, it can execute any command despite role permissions. Basically an override
- [x] Commands that return simple paragraphs to explain things such as "what is Trusted"
- [ ] "Serverinfo" command
- [x] Bot related stats and info command
- [ ] Messaging system between bot and users. Whenever someone new joins they get a message welcoming them with general stuff like reading the rules. Whenever someone is banned it PMs them the reason and directs them to further details and help

---

The following are things that are not necessarily needed but Sunny wants them. 

- [ ] When invited to a server, bot should be registered through DMs like RhinoBot is done. Registration only works if the person with the MasterID is doing the registering
- [ ] If the above works, then Blacklist of server IDs. This would prevent registration to go further if the server ID is blacklisted
- [ ] Global bans,  Bans a specified user on all servers the bot is present on

---

That's all I can think of at the moment.

**Comment by MarkusG** [comment]
Last 3 are practically impossible due to the bot's design and Discord's bot functionality. Bots don't accept invites and must be authed by a server member with MANAGE_SERVER. The bot is also not designed to work on multiple servers. It's designed to have one instance of the bot running per server on which it's active.

**Comment by khsunny786** [comment]
Can we not have more than one instance then? RhinoBot has the capability of working on several servers at once. I'm not saying that the Kratos has to be invited through invite links, we don't want it to. I want it to be run on several servers where I have the ability to add him using MANAGE_SERVER

**Comment by MarkusG** [comment]
I'll consider adding multi-server support, but for now it's designed to be single-server.

**Comment by khsunny786** [comment]
WE GOTTA MULTI SERVER

**Comment by ghost** [comment]
@MarkusGordathian  Multi Server is great idea for the pipe line 💯

**Comment by khsunny786** [comment]
Added a new requirement at the end of the list @MarkusGordathian

**Comment by MarkusG** [comment]
Commenting to test webhook

**Comment by MarkusG** [comment]
Tag module added in https://github.com/MarkusGordathian/Kratos/commit/fce63338759c50541cd97a9248d967f71c33a36d

**Comment by MarkusG** [comment]
Every item in the list that I intend to add has been added.
