### ISSUE TITLE
Add a snazzy logo.

### ISSUE THREAD

**Issue by MarkusG** [MarkusGordathian/Kratos#13]
Probably something Greek-mythology themed, seeing as the bot's name is Kratos. Suggestions welcome.

**Comment by khsunny786** [comment]
Current logo is fine for now

**Comment by MarkusG** [comment]
This is for the bot as a whole, not specific to the /r/teenagers server.

**Comment by khsunny786** [comment]
![sticky](https://cloud.githubusercontent.com/assets/13251152/21966357/86030f30-db69-11e6-9a8e-da4978b3db46.png)

**Comment by MarkusG** [comment]
Where's the downvote button on GitHub????

**Comment by khsunny786** [comment]
ur a slut mark

**Comment by ghost** [comment]
working on this.

**Comment by Alikarmine** [comment]
Hmm, I could work on this. Could I make a reference to the Kratos character from the God of War franchise in the logo?

**Comment by MarkusG** [comment]
No. I'd prefer something Greek-themed. I suggest a flat/material design character from the Greek alphabet.

**Comment by Alikarmine** [comment]
Alright, sure.

**Comment by MarkusG** [comment]
Closing this and merging #31 if no other logos are proposed by June 14th, 2017 at 23:00 PST.

**Comment by MarkusG** [comment]
Resolved in #31
