### ISSUE TITLE
Disabling ratelimit crashes the bot with a NullReferenceException

### ISSUE THREAD

**Issue by MarkusG** [MarkusGordathian/Kratos#14]
Setting the limit interval seems broken too.

**Comment by ghost** [comment]
I think maybe not give the user ability to disable ratelimit due to abuse.

https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/Rate_Limits.md

**Comment by MarkusG** [comment]
It's impossible to circumvent Discord's ratelimits. This is a ratelimit set by the bot which will mute people for sending messages too quickly. Enabling and disabling are only for people who have the permission.

**Comment by ghost** [comment]
@MarkusGordathian oh okay I see, well I will debug see if I can find the issue.

**Comment by MarkusG** [comment]
Not sure why this was broken before or what fixed it. Let's just close this issue and hope I don't have to reopen it.
