### ISSUE TITLE
CommandHandler

### ISSUE THREAD

**Issue by ghost** [MarkusGordathian/Kratos#16]
Hey @MarkusGordathian,

Sorry for being a bug but i'm still having that issue is the switch statement in commandhandler.

I do have the latest sdk now etc problem still there check command handler below maybe you can tweak it? I'm sure you not having this problem but would help.

https://github.com/Kwoth/NadekoBot/blob/dev/src/NadekoBot/Services/CommandHandler.cs

**Comment by MarkusG** [comment]
If you're still having the problem yourself, replace the pattern matching with the simpler form of `case ExecuteResult:` and manually cast it in the case block.

**Comment by ghost** [comment]
@MarkusGordathian Yes, Thanks I am busy working on improving the command handler

**Comment by MarkusG** [comment]
@di48l069 are you currently working on something you're planning to PR? I want to close this issue. The CommandHandler doesn't need any improvements in my opinion.

**Comment by ghost** [comment]
You may close it, working on something else related to kratos

Get Outlook for Android<https://aka.ms/ghei36>




On Tue, Jan 24, 2017 at 5:07 AM +0200, "Mark Gross" <notifications@github.com<mailto:notifications@github.com>> wrote:


@di48l069<https://github.com/di48l069> are you currently working on something you're planning to PR? I want to close this issue. The CommandHandler doesn't need any improvements in my opinion.
