### ISSUE TITLE
Make Program.cs way less ugly

### ISSUE THREAD

**Issue by MarkusG** [MarkusGordathian/Kratos#17]
Comments rather than regions, remove unnecessary fields.
Seriously what the hell was I thinking...

**Comment by Daniele122898** [comment]
thanks

**Comment by Sentinent** [comment]
succ

**Comment by Flamanis** [comment]
Get on it brah. You know you want to!

**Comment by MarkusG** [comment]
I also want to procrastinate and play Overwatch and derank into a depression.

**Comment by Daniele122898** [comment]
play CS:GO with me. thats the better choice

**Comment by MarkusG** [comment]
I used to play CS:GO until I stopped.

**Comment by Flamanis** [comment]
If you wanna play some overwatch, I'll play to kick yo ass

**Comment by Daniele122898** [comment]
i used to play overwatch. untill i stopped. was fun

**Comment by MarkusG** [comment]
Addressed in https://github.com/MarkusGordathian/Kratos/commit/7d6f8cb1dc34e8de028f0c3336212b1f40bfffcd. Decided to leave the private fields in as they're not too much clutter and there's no huge disadvantage to having them.
